#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: LGPL-3.0-or-later
#++

module Rooibos
  module Router
    # Observe rule - matches messages, handles, and continues processing.
    class Observe < Data
      include Rule

      attr_reader predicate: predicate
      attr_reader action: action
      attr_reader guard: Guard

      # Applies the action and returns a Transition.
      def apply: (message, _DataModel, Routes) -> Transition
    end
  end
end
