#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: LGPL-3.0-or-later
#++

module Rooibos
  module TestHelper
    def validate_rooibos_command!: (Runtime::_MaybeCommand) -> nil

    # Fails if any Command::Error is present in the messages array.
    # Relies on Minitest's flunk method being available in the including class.
    def assert_no_command_errors: (Array[untyped] messages, ?String? msg) -> void
  end
end
