#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: LGPL-3.0-or-later
#++

module RatatuiRuby
  module Tea
    # Convenient short aliases for Tea APIs.
    module Shortcuts
      # Short alias for Command.
      module Cmd
        def self.exit: () -> Command::Exit
        def self.sh: (String command, Symbol | Class tag) -> Command::System
        def self.map: (Command::execution inner_command) { (Array[untyped]) -> Array[untyped] } -> Command::Mapped
      end
    end
  end
end
