#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: LGPL-3.0-or-later
#++

module RatatuiRuby
  module Tea
    module TestHelper
      def validate_tea_command!: (Runtime::_MaybeCommand) -> nil
    end
  end
end
