#!/usr/bin/env ruby
# frozen_string_literal: true

#--
# SPDX-FileCopyrightText: 2026 Kerrick Long <me@kerricklong.com>
# SPDX-License-Identifier: LGPL-3.0-or-later
#++

require "rooibos/cli"
Rooibos::CLI.call(ARGV)
